name: Set AM Ratelimit config

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy"
        required: true
        default: "DES-INTRANET"
        type: choice
        options:
          - DES-IAM
          - DES-INTRANET

env:
  DESTINATION_PATH: "/path/to/destination"

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test enviroment
        run: echo ${{ vars.SSH_HOST }}
